version: '3'

services:
  api:
    build: ./
    environment:
      DEVICES_DIR: /devices
      CERTS_DIR: /certs
    volumes:
      - ${DATA_DIR-./data}/devices:/devices
      - ${DATA_DIR-./data}/certs:/certs:ro
    ports:
      - ${API_PORT-80}:8000
    restart: always
