version: '3.8'
networks:
  stealthy_local:
volumes:
  virtualenv_cache:
services:
  reference_server:
    build:
      context: ./provision/docker/backend/local
      dockerfile: Dockerfile
    user: ${DOCKER_UID:-1000}
    hostname: reference_server
    volumes:
      - ./backend:/srv/http
      - virtualenv_cache:/data/pypoetry
    env_file:
      - .environment/local/backend
    ports:
      - 0.0.0.0:80:8000
    networks:
      - stealthy_local
